# This workflow runs commit to the main branch in the repository.
# 
# This workflow will:
# - Verify the required variables and secrets are set in this GitHub Repository
# - Install node
# - Install the dependencies for the portal
# - Verify Snyk code scans pass (this is required)
# - Publish the built portal into an S3 bucket
#
# This workflow requires the following variables set in this repository's settings:
# S3_BUCKET                 -> The S3 bucket to publish the portal to
# SOURCE_DIRECTORY          -> The source directory for the portal within this repository
# SNYK_AUTH                 -> A token to authenticate to Snyk for scans
# 
# The final S3 bucket location will be:
# s3://S3_BUCKET/portals/REPOSITORY_NAME/versions/latest/
name: Momentum Portal Publish (Main Commits)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'portal/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-portal:
    name: Build and Publish Portal to S3
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Determine the Repository Name of where this Action is running
      # GHA does not conveniently set a context variable with *only* the Repository Name
      - name: Set Repository Name
        id: repo_name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> "$GITHUB_OUTPUT"

      # Verify we were able to parse out the repository name
      - name: Fail if Repository Name Not Set
        if: ${{ !steps.repo_name.outputs.REPO_NAME }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('The REPO_NAME value was not set in the github actions outputs.')
      
      # Verify we have an S3 bucket set in the Repository Variables
      - name: Fail if S3 Bucket Not Set
        if: ${{ !vars.S3_BUCKET }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('The S3_BUCKET variable was not set in the Repository Settings.')

      # Verify we have a build location set
      # This is variablized, as the portal build location could be different per repository
      - name: Fail if Source Directory Not Set
        if: ${{ !vars.SOURCE_DIRECTORY }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('The SOURCE_DIRECTORY variable was not set in the Repository Settings.')

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/${{ steps.repo_name.outputs.REPO_NAME }}-github-oidc
          aws-region: us-east-1

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Run Yarn Install
        working-directory: ${{ vars.SOURCE_DIRECTORY }}
        run: yarn install

      # Build the portal
      - name: Run Yarn Build
        working-directory: ${{ vars.SOURCE_DIRECTORY }}
        run: yarn build

      # Verify Snyk Scans Pass
      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH }}
        with:
          args: ${{ vars.SOURCE_DIRECTORY }}/ --severity-threshold=critical

      # Copy our built portal to the S3 bucket
      - name: Deploy to S3
        working-directory: ${{ vars.SOURCE_DIRECTORY }}
        run: |
          aws s3 sync \
          ./build \
          s3://${{ vars.S3_BUCKET }}/portals/${{ steps.repo_name.outputs.REPO_NAME }}/versions/latest/ \
          --cache-control=\"must-revalidate,max-age:0\" --delete